version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:8888"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4221345
      MYSQL_DATABASE: patisserie
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
